# Generated by Django 5.0.1 on 2024-01-08 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('goal', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('debt', 'DEBT'), ('food', 'FOOD'), ('hobbies', 'HOBBIES'), ('rent', 'RENT'), ('saving', 'SAVING'), ('medication', 'MEDICATION'), ('subscription', 'SUBSCRIPTION'), ('others', 'OTHERS')], max_length=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.budget')),
            ],
        ),
    ]
