# Generated by Django 5.0.1 on 2024-01-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_budget_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='session_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
